package com.system
/**
 * Generated by the Shiro plugin. This interceptor class protects all URLs
 * via access control by convention.
 */
class ShiroSecurityInterceptor {

    //customize me
    int order = HIGHEST_PRECEDENCE+200

    ShiroSecurityInterceptor(){
        matchAll().excludes(controller: "index")
    }
    boolean before() {

        if(response.status==500) {
            redirect(controller: "error",action: "error")
            return false
        }

        println "=======Shiro iterceptor========"
        if (!controllerName) return true
        accessControl(auth:true)
    }
    void afterView() {
    }
}
